export const BrowsingAlbumSearchActionType = {
    ARTIST_ALBUM_LOADING: "ARTIST_ALBUM_LOADING",
    ARTIST_ALBUM_LOADED: "ARTIST_ALBUM_LOADED",
    ARTIST_ALBUM_NOT_LOADED: "ARTIST_ALBUM_NOT_LOADED"
}