export const ArtistSearchActionType = {
    SEARCH: "SEARCH",
    ARTIST_LOADING: "ARTIST_LOADING",
    ARTIST_LOADED: "ARTIST_LOADED",
    ARTIST_NOT_LOADED: "ARTIST_NOT_LOADED",
    VALIDATION_ERR: "VALIDATION_ERR"
}